#! /bin/bash
if [[ ! -f /etc/ssh/ssh_host_rsa_key ]]; then
  echo 'root:dummy_passwd' | chpasswd
  cd /etc/ssh
  ssh-keygen -A
fi;
chmod 700 /root/.ssh
chmod 644 /root/.ssh/authorized_keys
chmod 600 /root/.ssh/id_rsa
chmod 644 /root/.ssh/id_rsa.pub
${process.env.PRIMARY !== "true" ? 'exec /usr/sbin/sshd -ddd -D' : ''}
