---
version: '3.4'
services:
  primary:
    image: respite:develop
    build: .
    env_file: .env
    privileged: true
    volumes: 
    #   - "./devdb:/root/pdns"
      - ./gui:/gui
    ports:
      # gui/pai
      - "8080:8080"
      # memhunt
      - "8081:8081"
      # dns
      - "5354:53/udp"
    environment:
      SELF: 'primary'
      NODES: 'primary, secondary, tertiary'
      PRIMARY: 'true'
    networks:
      - respite
  secondary:
    image: respite:develop
    build: .
    env_file: .env
    ports:
      - "5355:53/udp"
    environment:
      NODES: 'primary, secondary, tertiary'
      SELF: 'secondary'
    networks:
      - respite
  tertiary:
    image: respite:develop
    build: .
    env_file: .env
    ports:
      - "5356:53/udp"
    environment:
      NODES: 'primary, secondary, tertiary'
      SELF: 'tertiary'
    networks:
      - respite
networks:
  respite:
