#! /bin/bash
# ${Math.random()}
${( () => {
  const nodes = process.env.NODES.split(',').filter(node => node !== process.env.SELF).map(s => s.trim());
  return nodes.map((node, idx) => `${idx === nodes.length - 1 ? 'exec ' : ''}rsync -e "ssh -p 23" -a /root/pdns/op.log root@${node}:/root/pdns/op.log`).join('\n');
})()}
